name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        VERSION=$(date +%s)
        docker build . --file al2/x86_64/standard/1.0/Dockerfile --tag al2:${VERSION}
        docker login docker.pkg.github.com -u ${{ env.GITHUB_ACTOR }} -p ${{ secrets.GITHUB_TOKEN }}
        docker tag al2:${VERSION} docker.pkg.github.com/${{ env.GITHUB_REPOSITORY }}/al2:${VERSION}
        docker push docker.pkg.github.com/${{ env.GITHUB_REPOSITORY }}/al2:${VERSION}
      
