name: Docker Image CI

on: [push]

jobs:
  test-action-ubuntu:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: johnhanks1/actions/docker-gpr@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ubuntu
          dockerfile-location: ubuntu/standard/2.0
  test-action-al2:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: johnhanks1/actions/docker-gpr@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: al2
          dockerfile-location: al2/x86_64/standard/1.0
  
      


      
      
