name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      run:  docker login docker.pkg.github.com -u ${GITHUB_ACTOR} -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build AL2 Docker image
      run: |
        cd al2/x86_64/standard/1.0
        VERSION=$(date +%s)
        docker build . --tag al2:${VERSION}
    - name: Push Docker Image
      run: |
        docker login docker.pkg.github.com -u ${GITHUB_ACTOR} -p ${{ secrets.GITHUB_TOKEN }}
        docker tag al2:${VERSION} docker.pkg.github.com/${GITHUB_REPOSITORY}/al2:${VERSION}
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/al2:${VERSION}

      
      
